# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-16 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.AddField(
            model_name='students',
            name='chem',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='cs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='eng',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='maths',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='phy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
