# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-19 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InwardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amountINR', models.DecimalField(decimal_places=2, max_digits=15)),
                ('GLS_commission', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Ex_commission', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Service_tax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Date', models.DateField()),
                ('App', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashB.Inward')),
            ],
        ),
        migrations.CreateModel(
            name='Outward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OutwardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountForeign', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amountINR', models.DecimalField(decimal_places=2, max_digits=15)),
                ('GLS_commission', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Service_tax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Date', models.DateField()),
                ('curr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashB.Outward')),
            ],
        ),
    ]
