# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inwarddata',
            old_name='App',
            new_name='App_name',
        ),
        migrations.RenameField(
            model_name='outwarddata',
            old_name='curr',
            new_name='Currency',
        ),
    ]
