# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashB', '0002_auto_20170619_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inwarddata',
            old_name='App_name',
            new_name='App',
        ),
        migrations.RenameField(
            model_name='outwarddata',
            old_name='Currency',
            new_name='curr',
        ),
    ]
